name: Build, Test, and Analyze

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and run tests
        run: mvn clean verify org.pitest:pitest-maven:mutationCoverage

      - name: Check testing coverage
        run: |
          chmod +x .github/scripts/summary.sh
          bash .github/scripts/summary.sh
        shell: bash

      - name: Check PIT Mutation coverage
        run: |
          chmod +x .github/scripts/pit_score.sh
          bash .github/scripts/pit_score.sh
        shell: bash